### ISSUE TITLE
Complete terminology for OpenMind concepts

### ISSUE THREAD

**Issue by lunaroyster** [grey-software/OpenMind#9]
Once I complete the use cases, I will begin writing the terminology for the ideas we seek to introduce. I believe getting the terminology right will save us from talking past each other.

First draft due 2/21/2020

**Comment by ArsalaBangash** [comment]
Getting the terminology right isn't all on you. After you complete your use cases, we'll look over them together to figure out a common language we can use to talk about all the data structures involved.

**Comment by lunaroyster** [comment]
I agree! I think I should put to the letter what I think, and we can discuss it! I will get this done today (right after the usecases)

**Comment by lunaroyster** [comment]
Here's the current state of [terminology](https://www.notion.so/openmap/Terminology-WIP-2834be61d2ca4577be00cdbba49727b1)
